---
title: "Dimension reduction"
author: "Dave Tang"
date: "`r Sys.Date()`"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=10000)
```

Dimension reduction is useful for identifying correlated features and reducing the data size, which is very useful for visualising large datasets.

PCA.

```{r pca}
pca <- prcomp(iris[, 1:4])
my_col <- as.integer(iris$Species)

plot(pca$x, col = my_col, pch = 16)
```

t-SNE default perplexity of 30.

```{r tsne}
if(!require(tsne)){
  install.packages("tsne")
}
library(tsne)

tsne_ <- tsne(iris[, 1:4])

plot(tsne_, col = my_col, pch = 16)
```

Perplexity of 20.

```{r tsne_p20}
tsne_p20 <- tsne(iris[, 1:4], perplexity = 20)

plot(tsne_p20, col = my_col, pch = 16)
```

Perplexity of 40.

```{r tsne_p40}
tsne_p40 <- tsne(iris[, 1:4], perplexity = 40)

plot(tsne_p40, col = my_col, pch = 16)
```

Perplexity of 50.

```{r tsne_p50}
tsne_p50 <- tsne(iris[, 1:4], perplexity = 50)

plot(tsne_p50, col = my_col, pch = 16)
```

UMAP default settings.

```{r umap_defaults}
if(!require(umap)){
  install.packages("umap")
}
library(umap)
umap.defaults
```

UMAP with default settings.

```{r umap}
umap_ <- umap(iris[, 1:4])

plot(umap_$layout, col = my_col, pch = 16)
```

Adjust number of neighbours.

```{r umap_custom}
umap_conf <- umap.defaults
umap_conf$n_neighbors <- 20

umap_n20 <- umap(iris[, 1:4], config = umap_conf)
plot(umap_n20$layout, col = my_col, pch = 16)
```
