---
title: "Simulation"
author: "Dave Tang"
date: "`r Sys.Date()`"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

[Monte Carlo simulation](https://en.wikipedia.org/wiki/Monte_Carlo_method) are useful for estimating probablities and relies on repeated random sampling to generate a probability distribution. You may have heard of the [Monty Hall problem](https://en.wikipedia.org/wiki/Monty_Hall_problem): 

    Suppose you're on a game show, and you're given the choice of three doors: Behind one door is a car; behind the others, goats. You pick a door, say No. 1, and the host, who knows what's behind the doors, opens another door, say No. 3, which has a goat. He then says to you, "Do you want to pick door No. 2?" Is it to your advantage to switch your choice?

Let's simulate the Monty Hall problem 50,000 times each, for **not switching** and for **switching** to see if it is advantageous to switch.

```{r monty_hall_simulation}
monty_hall_game <- function(switch = TRUE){
  # randomly assign what's behind the three doors
  doors <- 1:3
  behind <- sample(c("car", "goat", "goat"))
  door_car <- doors[behind == "car"]
  
  # randomly pick a door
  my_pick <- sample(doors, 1)
  
  # if we picked the door with the car, randomly show one of the doors with the goat
  if(my_pick == door_car){
    door_show <- sample(doors[-my_pick], 1)
  # if we picked a door with a goat, show the door with the other goat
  } else {
    door_show <- doors[-c(my_pick, door_car)]
  }
  
  # if we choose to switch
  if(switch == TRUE){
    final_pick <- doors[-c(my_pick, door_show)]
  # if we stick with our original pick
  } else {
    final_pick <- my_pick
  }
  
  final_pick == door_car
}

num_rep <- 50000

result_no_switch <- replicate(num_rep, monty_hall_game(FALSE))
result_switch <- replicate(num_rep, monty_hall_game(TRUE))

paste0("If we stick with our original choice, our success rate is ", mean(result_no_switch) * 100, "% in ", num_rep, " tests.")
paste0("If we switch from our original choice, our success rate is ", mean(result_switch) * 100, "% in ", num_rep, " tests.")
```

From the Monte Carlo simulation, we see that if we don't switch, we get the door with the prize (car) 33% of the time. This makes sense because if we disregard the switch, there is a 1/3 chance of picking the prize. If we make the switch, we get the door with the prize 66% of the time! This also makes sense because before the switch, there is a 33% chance of getting the prize door. Therefore 66% of the time, the prize door is among the other two doors that you didn't pick. When the host opens the non-prize door (out of the two you didn't pick), the remaining door has a 66% chance of being the prize door.
